### ISSUE TITLE
Movie Audio Thread gets stuck in loop when exiting.

### ISSUE THREAD

**Issue by Sebanisu** [MaKiPL/OpenVIII#38]
When I exit while a video is playing the game doesn't quit. I pushed pause on the debugger and it was in the thread. since audio isn't playing the number of samples never changes so the loop goes on forever. I think to fix I might need to move the thread to ffcc class. So on dispose it kills the thread. Or I need to just kill the thread when I quit the game.

I think dispose is the better method. Though I was surprised it didn't throw an exception. :P

I'll put a fix in before my next pull request.

**Comment by Sebanisu** [comment]
hmm thats odd. dispose isn't called? I thought it would be called when I exit.

**Comment by Albeoris** [comment]
- Any threads that don't make sense after stopping the main should be started with IsBackground flag.
- Start the thread only if you need full control over the thread: instant start and the ability to kill the thread. Otherwise, use task.
- An unhandled exception that happened in the thread will bring crush the game. If this is a critical functionality, you need to catch exceptions and correctly complete the process, provide enough information about the issue.
- Thread.Abort () throws a ThreadAbortException into the thread. This exception ignores any delays, but is processed in finaly blocks (including Dispose), so it can also take time. If the game does not close, then it is not recommended to kill the streams - an exception can occur at any time and break down future challenges. For example, no one protects a List or Dictionary from a ThreadAbortException during the process of adding a new item (not an atomic operation).
- Freeing memory and closing resources during an unmanaged call to a device can lead to a driver / codec failure (although this is usually very well protected).

Therefore, if you need to stop the long-lived flow, the most correct way is to cancel the current operation and break the cycle. Most often for this purpose use CancellationToken. But in this case, the token becomes a synchronization context that needs to be dragged through all calls or stored in a shared field.

**Comment by Sebanisu** [comment]
The threads job is see if the audio buffer has at least 100 chunks of audio data. If it is full it sleeps for a few ms and tries again. It does this till EOF. The endless loop happens when the audio stops playing so the buffer doesn't empty 

Are you saying I should set a variable to terminate the thread. I was going to check for isdisposed but the deconstructor and dispose didn't run on there own. So isdisposed was false.

Anyhow thanks for the information. I am just on my lunch break. I will read in more detail later.

**Comment by Sebanisu** [comment]
I have switched to a Task and added a cancellationtoken. Seems to work fine.

I have observed a new exception but it's rare and possibly unrelated to this.
https://github.com/MaKiPL/OpenVIII/issues/47

I'm going to close this because this issue is no longer a problem. Thank you for the help :)
