### ISSUE TITLE
Coding Conventions / Architecture

### ISSUE THREAD

**Issue by benjaminfoo** [MaKiPL/OpenVIII#98]
I think some parts of the project need some clarification on how the code should be structured (using camel-case for the code, some kind of formatting, comments, amount of magic numbers, etc.), for example - the file module_world_debug.cs should be called Module_World_Debug.cs or ModuleWorldDebug.cs. There is also a lot of static code used where an OOP approach maybe would be a better fit.

Another thing which I noted is the low amount of documentation (meaning and uses of classes as a header-comment, meaning of members in classes, method-comments, etc.) - this should be refactored in order to lower the amount of work for new people within the project.

**Comment by Sebanisu** [comment]
Sorry for the mess heh. The menu module ballooned as I started adding new screens. I was going to go back over it when I when I had all the screens done. I am kinda a learn as I go kinda person. I had some done some coding but not at this scale.

**Comment by benjaminfoo** [comment]
No reason to apologize :) - sometimes the urge to create progress in a project like this is so top prio, that everything else simply doesnt matter, or anything else is just more important. However, I think the amount of technical debt should be kept at a low level and the things I mentioned are, at this level, still very manageable.

Here is a list of stuff that needs to be done / talked about:

- [ ]  What are the naming conventions for classes? (Starting with an uppercase, use "_" or "." as a name seperator or simple none (something like module_world_debug should be named as ModuleWorldDebug.cs from my pov, ...) - some class-names dont match with the file-name (module_world_debug.cs as file, Module_world_debug as class, ...)
- [ ] The amount of static classes, static class members, etc. - I think that a lot of code could be architectured in a simple OOP way, the modules for example.
- [ ] There is nearly no documentation available for the project, this makes it extremely time-consuming for other people to work on this project. Some chats in the discord has helped quite a lot, this knowledge should be written down somewhere.
- [ ] A LOT of hardcoded numbers are used, these should be replaced with constants or at least explained why this number is used.

**Comment by MaKiPL** [comment]
Ad.1+2 - naming conventions are not followed- at least not in the older classes. They should be changed
Ad.3 - in many situations this is intentional. The modules can be changed in real-time meaning they have to store some variables even when they are not used. Example is changing the module from field to battle or from field to cardgame and back. Even though that the module is no longer used when example in card module, then as soon as the module ends it gets back to the same state of field it was just before jumping into the cards. It's the same behaviour as in vanilla. Some modules even before init can talk or query variables of static properties of others. OOP is mainly used for creating objects that are mostly created and destroyed afterward like enemies on the battle module. 
Ad.4 I'll be working on it
Ad.5 Sure, good point
Ad.6 Yeah, the same Vertex/Vec3 struct for example is copied over at least three different classes- bad design

**Comment by Sebanisu** [comment]
Ad.6 I've seen this where like structs exist in XNA but we had a custom struct for it. In Tim2.cs and Tex.cs for color, so i changed it to work with the XNA color struct. Might be other examples of this. Because the classes were ported from projects without xna.

**Comment by benjaminfoo** [comment]
I think we should introduce something like a vector2 and vector3 class for the 6th point and use this instead, could be beneficial for caching.

**Comment by Sebanisu** [comment]
XNA has a vector2 and vector3 struct 
https://docs.microsoft.com/en-us/previous-versions/windows/silverlight/dotnet-windows-silverlight/bb199660(v%3Dxnagamestudio.35)
https://docs.microsoft.com/en-us/previous-versions/windows/silverlight/dotnet-windows-silverlight/bb199670(v=xnagamestudio.35)
Do you mean we shouldn't use those?

**Comment by benjaminfoo** [comment]
No, we should use these if they are already implemented.

**Comment by benjaminfoo** [comment]
As all of the involved people within the project were interested in an architecture, i'd like to close this issue and create a new one with ideas / concepts for an alternative
